# Generated by Django 3.0.6 on 2020-06-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
