# Generated by Django 3.0.6 on 2020-06-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('language', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='profile/projects')),
            ],
        ),
    ]
